server:
  port : 8081

spring:
  application:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

storage:
  path: ${STORAGE_PATH:./uploads}
  delete-cycle-time-in-minutes: ${DELETE_CYCLE_TIME_IN_MINUTES:10}

springdoc:
  swagger-ui:
    path: /docs